### ISSUE TITLE
Add transfers for incoming and outgoing calls

### ISSUE THREAD

**Issue by 9mido** [TwilioDevEd/voice-javascript-sdk-quickstart-python#4]
It would be awesome if this github project had the feature of being able to type in another phone number or twilio client identity into the form and be able to click a transfer button to transfer the current incoming or outgoing call recipient to this new phone number.

There should be a fallback in case the number we are transferring to does not answer. In other words, we should be able to transfer again if the number we are transferring does not answer. Being stuck in a transferred to conference call and not being able to transfer again would get us stuck with nowhere to go.

**Comment by bld010** [comment]
Hi @9mido ... I can see how this is a good use case, but falls outside the scope of a quickstart (which has the most common use cases and is mainly for the purpose of learning the product). This type of use case would require a different backend TwiML setup and quite a bit more frontend work, which would make it much harder for new Twilio customers to understand.
